# Jekyll settings
timezone: America/New_York

# Site settings
title: "Oliver Steele | Blog"
email: steele@osteele.com
# description: > # this means to ignore newlines until "baseurl:"
#   Languages of the real and artificial.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.osteele.com" # the base hostname & protocol for your site
timezone: America/New_York
twitter_username: osteele
github_username:  osteele

permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - config
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts
  - templates
  - TODO
